resources:
  - name: dwpdigital-dataworks-data-egress
    type: registry-image-resource
    source:
      repository: dwpdigital/dataworks-data-egress
    check_every: 5m

  - name: ecr-dwpdigital-dataworks-data-egress-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-data-egress"

  - name: ecr-dwpdigital-dataworks-data-egress
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-data-egress"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-dataworks-data-egress-dev
    serial_groups: [dataworks-data-egress]
    plan:
      - get: dwpdigital-dataworks-data-egress
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-data-egress-dev
        params:
          image: "dwpdigital-dataworks-data-egress/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-dataworks-data-egress
    serial_groups: [dataworks-data-egress]
    plan:
      - get: dwpdigital-dataworks-data-egress
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-data-egress
        params:
          image: "dwpdigital-dataworks-data-egress/image.tar"
        attempts: 3
