name: Test and scan

on: pull_request

env:
  IMAGE_NAME: dwpdigital/dataworks-data-egress

jobs:
  test-build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: integration-tests
        run: |
          make certificates
          make integration-tests

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
